import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Auth from "~/components/Auth";
import Playlist from "~/components/Playlist";
import PlaylistImporter from "~/components/PlaylistImporter";

const Home: NextPage = () => {
  const session = useSession().data;
  const { data: playlists } = api.playlists.all.useQuery();

  return (
    <>
      <Head>
        <title>Blind Medley</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center min-h-screen bg-light bg-dots-pattern bg-no-repeat bg-cover text-grey">
        <div className="absolute top-5 right-5">
          <Auth />
        </div>
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-bold text-center text-grey">
            Blind Medley
          </h1>
          {session?.user && (
            <p className="text-center text-2xl text-white">
              {session && (
                <div className="flex items-center gap-4">
                  <Image
                    src={session.user.image!}
                    alt={session.user.name!}
                    width={50}
                    height={50}
                    className="rounded-full"
                  />
                  <span className="text-grey">{session.user.name}</span>
                </div>
              )}
            </p>
          )}
          {session?.user.role === "ADMIN" && <PlaylistImporter />}
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-8">
            {playlists ? (
              playlists.map((playlist, idx) => (
                <Playlist key={idx} playlist={playlist} />
              ))
            ) : (
              <p>Loading</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
